### ISSUE TITLE
View my weekly tasks

### ISSUE THREAD

**Issue by Dhwani-Patel-7** [Rashib06/Task-box#18]
As a user, I want to view my current week tasks

**Comment by Rashib06** [comment]
1.Open menu bar
2.Select weekly tasks option
3.View whole week's tasks on a new screen

**Comment by Rashib06** [comment]
issue #18 close
https://user-images.githubusercontent.com/73277301/220233116-eb0d238e-b4aa-4442-99c2-9da01bdfdcc7.mov
