### ISSUE TITLE
View my monthly tasks

### ISSUE THREAD

**Issue by Dhwani-Patel-7** [Rashib06/Task-box#19]
As a user, I want to see all the monthly tasks only on my screen

**Comment by Rashib06** [comment]
1.Open menu bar
2.Select monthly tasks option
3.View whole month's tasks on the screen

**Comment by Rashib06** [comment]
https://user-images.githubusercontent.com/73277301/229653678-6cbadb37-073f-421f-8f47-2b523851dc50.mov

User can view all task of the current month
