### ISSUE TITLE
Save the task 

### ISSUE THREAD

**Issue by Dhwani-Patel-7** [Rashib06/Task-box#4]
As a user, i want to either save the task or go back

**Comment by Rashib06** [comment]
1. User saves a task
2. Store the information of saved task 
3. Display task in the list or screen with a checkbox

**Comment by Rashib06** [comment]
Closed saving a task
User can save a task

**Comment by Rashib06** [comment]
https://user-images.githubusercontent.com/73277301/217109007-9f4ed120-2fb7-4aa8-b6d2-ae063845be78.mov
