### ISSUE TITLE
Check/ uncheck  a task

### ISSUE THREAD

**Issue by Dhwani-Patel-7** [Rashib06/Task-box#6]
As a user, I want to mark my task as completed or incomplete

**Comment by Rashib06** [comment]
1. Click on the checkbox ☑️ of a task to mark it as completed

**Comment by Dhwani-Patel-7** [comment]
issue#6 completed

https://user-images.githubusercontent.com/111162262/226496710-43bb0406-4474-4106-9146-5b4e2ce63b5d.mov
