### ISSUE TITLE
Delete a specific task

### ISSUE THREAD

**Issue by Dhwani-Patel-7** [Rashib06/Task-box#7]
As a user, I want to delete a selected task

**Comment by Rashib06** [comment]
1. Select a specific task
2. Click on delete option 
3. Remove that task from screen

**Comment by Dhwani-Patel-7** [comment]
https://user-images.githubusercontent.com/111162262/217110698-d0e95b4a-4912-4f7b-bcfc-4bd5d9921dd4.mov

Closed #7
